FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

COPY /*.sln ./
COPY /Application/Application.csproj ./Application/
COPY /Domain/Domain.csproj ./Domain/
COPY /Infrastructure.Identity/Infrastructure.Identity.csproj ./Infrastructure.Identity/
COPY /Infrastructure.Persistence/Infrastructure.Persistence.csproj ./Infrastructure.Persistence/
COPY /WebApi/WebApi.csproj ./WebApi/

RUN dotnet restore
COPY /. ./
RUN dotnet publish ./WebApi/WebApi.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS runtime
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "WebApi.dll"]
